.

diff --git a/usr/bin/dm-packaging-helper-script b/usr/bin/dm-packaging-helper-script
--- a/usr/bin/dm-packaging-helper-script
+++ b/usr/bin/dm-packaging-helper-script
@@ -1465,12 +1465,22 @@ pkg_git_branch_checkout_trixie() {
    return 0
 }
 
-pkg_git_branch_fetch_all() {
+pkg_git_branch_fetch_upstream() {
+   pkg_git_branch_fetch_one "github-${batch_current_project_name,,}"
+}
+
+pkg_git_branch_fetch_arraybolt3() {
+   pkg_git_branch_fetch_one "ArrayBolt3"
+}
+
+pkg_git_branch_fetch_bot() {
+   pkg_git_branch_fetch_one "${DM_GITHUB_MIRROR}"
+}
+
+pkg_git_branch_fetch_one() {
    local origin_name_list package_remote_item
 
-   #origin_name_list=( "github-${batch_current_project_name,,}" )
-   origin_name_list=( "${DM_GITHUB_MIRROR}" )
-   origin_name_list=( "ArrayBolt3" )
+   origin_name_list=( "$@" )
 
    for package_remote_item in "${origin_name_list[@]}"; do
       dry_run_or_run git fetch -- "${package_remote_item}" &
@@ -1480,37 +1490,23 @@ pkg_git_branch_fetch_all() {
    return 0
 }
 
-pkg_git_branch_pull_upstream_master() {
-   local origin_name_list package_remote_item upstream_repo
+pkg_git_diff_and_merge_branch_upstream() {
+   pkg_git_diff_and_merge_branch "github-${batch_current_project_name,,}"
+}
 
-   if [ "${batch_current_project_name,,}" = "whonix" ]; then
-      upstream_repo=github-whonix
-   elif [ "${batch_current_project_name,,}" = "kicksecure" ]; then
-      upstream_repo=github-kicksecure
-   elif [ "${batch_current_project_name,,}" = "derivative-maker" ]; then
-      upstream_repo=github-kicksecure
-   else
-      printf '%s\n' "ERROR: batch_current_project_name wrong! (1)"
-      exit 1
-   fi
+pkg_git_diff_and_merge_branch_arraybolt3() {
+   pkg_git_diff_and_merge_branch "ArrayBolt3/trixie"
+}
 
-   for package_remote_item in "${origin_name_list[@]}"; do
-      dry_run_or_run git pull --ff-only --verify-signatures -- "${upstream_repo}" "${package_remote_item}" &
-      git_pid_label[$!]="pull ${package_remote_item} (${batch_current_package_reponame})"
-   done
-
-   return 0
+pkg_git_diff_and_merge_branch_bot() {
+   pkg_git_diff_and_merge_branch "${DM_GITHUB_MIRROR}/master"
 }
 
 pkg_git_diff_and_merge_branch() {
    #repo_skip 'derivative-maker' || return 0
 
-   ## TODO: remove
-   repo_skip 'usability-misc' || return 0
-
-   #origin_branch="github-${batch_current_project_name,,}/master"
-   origin_branch="${DM_GITHUB_MIRROR}/master"
-   origin_branch="ArrayBolt3/arraybolt3/trixie"
+   local origin_branch
+   origin_branch="$@"
 
    ## Use the fully qualified remote-tracking ref to avoid name
    ## collision with same-named tags.
@@ -1562,6 +1558,28 @@ pkg_git_diff_and_merge_branch() {
 
    ## Manually re-run script.
    exit
+}
+
+pkg_git_branch_pull_upstream_master() {
+   local origin_name_list package_remote_item upstream_repo
+
+   if [ "${batch_current_project_name,,}" = "whonix" ]; then
+      upstream_repo=github-whonix
+   elif [ "${batch_current_project_name,,}" = "kicksecure" ]; then
+      upstream_repo=github-kicksecure
+   elif [ "${batch_current_project_name,,}" = "derivative-maker" ]; then
+      upstream_repo=github-kicksecure
+   else
+      printf '%s\n' "ERROR: batch_current_project_name wrong! (1)"
+      exit 1
+   fi
+
+   for package_remote_item in "${origin_name_list[@]}"; do
+      dry_run_or_run git pull --ff-only --verify-signatures -- "${upstream_repo}" "${package_remote_item}" &
+      git_pid_label[$!]="pull ${package_remote_item} (${batch_current_package_reponame})"
+   done
+
+   return 0
 }
 
 ## Detects packages with Bash profile.d files, and adds symlink lines to zsh's
