Make compatible with hardened JSON parsing code in tb-updater, harden Tor Browser ARM64 JSON parsing

diff --git a/usr/bin/dm-packaging-helper-script b/usr/bin/dm-packaging-helper-script
--- a/usr/bin/dm-packaging-helper-script
+++ b/usr/bin/dm-packaging-helper-script
@@ -1909,9 +1909,10 @@ pkg_tor_browser_version_update() {
       current_tbb_version current_tbb_alpha_version tbb_dl_arm_page \
       tbb_arm_json current_tbb_arm_version
 
-   ## Source tb-updater version-parser script to get tbbversion function. Uses
-   ## environment variable RecommendedTBBVersions as input.
-   source "${derivative_maker_source_code_dir}/packages/kicksecure/tb-updater/usr/libexec/tb-updater/version-parser"
+   ## Source tb-updater version-validator script to get tbbversion function.
+   ## Uses environment variables RecommendedTBBVersions and
+   ## tbb_version_parse_as_arm64 as input.
+   source "${derivative_maker_source_code_dir}/packages/kicksecure/tb-updater/usr/libexec/tb-updater/version-validator"
 
    tbb_hardcoded_version_file="${derivative_maker_source_code_dir}/packages/kicksecure/tb-updater/usr/share/tb-updater/tbb_hardcoded_version"
    tbb_hardcoded_version_alpha_file="${derivative_maker_source_code_dir}/packages/kicksecure/tb-updater/usr/share/tb-updater/tbb_hardcoded_version_alpha"
@@ -1919,6 +1920,8 @@ pkg_tor_browser_version_update() {
    tbb_alpha_json_url='https://aus1.torproject.org/torbrowser/update_3/alpha/downloads.json'
    RecommendedTBBVersions="$(mktemp)"
    export RecommendedTBBVersions
+   tbb_version_parse_as_arm64='n'
+   export tbb_version_parse_as_arm64
 
    pushd "${derivative_maker_source_code_dir}/packages/kicksecure/tb-updater"
    git_status_last_line="$(git status | tail -n1)"
@@ -1949,11 +1952,15 @@ pkg_tor_browser_version_update() {
    ## a JS script, and parsing that JSON blob is tricky.
    tbb_dl_arm_page="$(2>/dev/null scurl --cert-status 'https://sourceforge.net/projects/tor-browser-ports/files/')";
    tbb_arm_json="$(grep 'net.sf.files' <<< "${tbb_dl_arm_page}" \
-         | sed 's/\s\+net\.sf\.files = //; s/;$//')"
-   current_tbb_arm_version="$(jq \
-      '[.[] | select(.name | test("^\\d+\\.\\d+\\.\\d+"))][0].name' \
-      <<< "${tbb_arm_json}" \
-      | sed 's/"//g')";
+      | sed 's/\s\+net\.sf\.files = //; s/;$//')"
+   echo "${tbb_arm_json}" > "${RecommendedTBBVersions}"
+
+   tbb_version_parse_as_arm64='y'
+   tbbversion || {
+      echo "${red}${bold}FATAL ERROR: Could not parse ARM64 TBB version JSON!${reset}"
+      exit 1
+   }
+   current_tbb_arm_version="${tbb_version}"
 
    safe-rm -f "${tbb_hardcoded_version_file}"
    echo "tbb_hardcoded_version=\"${current_tbb_version}\"" | sponge -a -- "${tbb_hardcoded_version_file}"
