.

diff --git a/usr/bin/dm-tbb-update b/usr/bin/dm-tbb-update
--- a/usr/bin/dm-tbb-update
+++ b/usr/bin/dm-tbb-update
@@ -16,8 +16,12 @@ source /usr/libexec/helper-scripts/git.sh
 derivative_maker_source_code_dir="$HOME/derivative-maker"
 
 version_check() {
+   if [ "${1,,}" = "" ]; then
+      printf "%s\n" "${red}${bold}FATAL ERROR: Invalid version (empty)!${reset}"
+      exit 1
+   fi
    if [ "${1,,}" = "unknown" ]; then
-      printf "%s\n" "${red}${bold}FATAL ERROR: Invalid version!${reset}"
+      printf "%s\n" "${red}${bold}FATAL ERROR: Invalid version (unknown)!${reset}"
       exit 1
    fi
 }
@@ -50,24 +54,24 @@ pkg_tor_browser_version_update() {
    popd
 
    ## tbbversion requires: ${RecommendedTBBVersions}
-   ## tbbversion sets: ${tbb_version}
+   ## tbbversion sets: ${tbb_version_stripped}
    2>/dev/null scurl --output "${RecommendedTBBVersions}" "${tbb_stable_json_url}"
    tbbversion || {
       printf "%s\n" "${red}${bold}FATAL ERROR: Could not parse stable TBB version JSON!${reset}"
       exit 1
    }
-   version_check "${tbb_version}"
+   version_check "${tbb_version_stripped}"
    # shellcheck disable=SC2154
-   current_tbb_version="${tbb_version}"
+   current_tbb_version="${tbb_version_stripped}"
 
    2>/dev/null scurl --output "${RecommendedTBBVersions}" "${tbb_alpha_json_url}"
    tbbversion || {
       printf "%s\n" "${red}${bold}FATAL ERROR: Could not parse alpha TBB version JSON!${reset}"
       exit 1
    }
-   version_check "${tbb_version}"
+   version_check "${tbb_version_stripped}"
    # shellcheck disable=SC2154
-   current_tbb_alpha_version="${tbb_version}"
+   current_tbb_alpha_version="${tbb_version_stripped}"
 
    safe-rm -f -- "${tbb_hardcoded_version_file}"
    printf "%s\n" "tbb_hardcoded_version=\"${current_tbb_version}\"" | sponge -a -- "${tbb_hardcoded_version_file}"
