.

diff --git a/usr/bin/dm-tbb-update b/usr/bin/dm-tbb-update
--- a/usr/bin/dm-tbb-update
+++ b/usr/bin/dm-tbb-update
@@ -15,6 +15,13 @@ source /usr/libexec/helper-scripts/git.sh
 ## XXX: hardcoded path
 derivative_maker_source_code_dir="$HOME/derivative-maker"
 
+version_check() {
+   if [ "$1,," = "unknown" ]; then
+      printf "%s\n" "${red}${bold}FATAL ERROR: Invalid version!${reset}"
+      exit 1
+   fi
+}
+
 pkg_tor_browser_version_update() {
    local tbb_hardcoded_version_file tbb_hardcoded_version_alpha_file \
       tbb_stable_json_url tbb_alpha_json_url \
@@ -46,6 +53,7 @@ pkg_tor_browser_version_update() {
       printf "%s\n" "${red}${bold}FATAL ERROR: Could not parse stable TBB version JSON!${reset}"
       exit 1
    }
+   version_check "${tbb_version}"
    # shellcheck disable=SC2154
    current_tbb_version="${tbb_version}"
 
@@ -54,6 +62,7 @@ pkg_tor_browser_version_update() {
       printf "%s\n" "${red}${bold}FATAL ERROR: Could not parse alpha TBB version JSON!${reset}"
       exit 1
    }
+   version_check "${tbb_version}"
    # shellcheck disable=SC2154
    current_tbb_alpha_version="${tbb_version}"
 
